import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { protect, wrap } from '../middleware/auth.js';
import * as auth from '../controllers/authController.js';
import * as st from '../controllers/studentController.js';
import * as fee from '../controllers/feeController.js';
import * as settings from '../controllers/settingsController.js';
import { notifications, announcements, monthlyReport, paymentsReport } from '../controllers/miscController.js';
const r = Router(); const admin = protect('admin'); const any = protect('admin', 'student');
r.post('/auth/login', rateLimit({ windowMs: 15 * 60 * 1000, limit: 20 }), wrap(auth.login));
r.post('/auth/fcm-token', protect('student'), wrap(auth.saveFcmToken));
r.get('/students', admin, wrap(st.list)); r.post('/students', admin, wrap(st.create));
r.get('/students/me', protect('student'), wrap(st.getOne));
r.put('/students/me', protect('student'), wrap(st.updateMe));
r.get('/students/:id', admin, wrap(st.getOne)); r.put('/students/:id', admin, wrap(st.update));
r.delete('/students/:id', admin, wrap(st.deactivate)); r.post('/students/:id/reset-password', admin, wrap(st.resetPassword));
r.get('/fees', any, wrap(fee.list)); r.post('/fees/generate', admin, wrap(fee.generateMonth));
r.put('/fees/:id', admin, wrap(fee.update)); r.post('/fees/remind-all', admin, wrap(fee.remindAll)); r.post('/fees/:id/remind', admin, wrap(fee.remind));
r.get('/payments', any, wrap(fee.payments.list)); r.post('/payments', admin, wrap(fee.payments.create));
r.get('/notifications', protect('student'), wrap(notifications.list));
r.put('/notifications/read-all', protect('student'), wrap(notifications.markAllRead));
r.put('/notifications/:id/read', protect('student'), wrap(notifications.markRead));
r.post('/notifications', admin, wrap(notifications.sendCustom));
r.get('/announcements', any, wrap(announcements.list)); r.post('/announcements', admin, wrap(announcements.create));
r.get('/reports/monthly', admin, wrap(monthlyReport)); r.get('/reports/payments', admin, wrap(paymentsReport));
r.get('/settings', admin, wrap(settings.get)); r.put('/settings', admin, wrap(settings.update));
r.post('/auth/change-password', any, wrap(auth.changePassword));
export default r;
